# items
# NOTE: 'index' is not used anywhere

itemDataList = {
    'potions': 
    [
        {
            'id': 0,
            'name': 'Normal Potion',
            'type': 'potion',
            'healing': 50,
            'value': 50,
            'stackable': True,
            'tier': 1,  
            'quantity': 0,
            'index': 0,
        },

        {
            'id': 1,
            'name': 'Powerful Potion',
            'type': 'potion',
            'healing': 150,
            'value': 100,
            'stackable': True,
            'tier': 2, 
            'quantity': 0,
            'index': 0,
        },

        {
            'id': 2,
            'name': 'Super Potion',
            'type': 'potion',
            'healing': 350,
            'value': 250,
            'stackable': True,
            'tier': 3, 
            'quantity': 0,
            'index': 0,
        },

        {
            'id': 3,
            'name': 'Hyper Potion',
            'type': 'potion',
            'healing': 550,
            'value': 400,
            'stackable': True,
            'tier': 4, 
            'quantity': 0,
            'index': 0,
        },

        {
            'id': 4,
            'name': 'Max Potion',
            'type': 'potion',
            'healing': 9999,
            'value': 600,
            'stackable': True,
            'tier': 5, 
            'quantity': 0,
            'index': 0,
        }
    ],

    'weapons':[
        {
            'id': 5,
            'name': 'Sword I',
            'type': 'weapon',
            'damage': [20, 48],
            'epCost': 3,
            'critChance': 0.15,
            'value': 200,
            'stackable': False,
            'tier': 1,
            'quantity': 0,
            'index': 0,
        },

        {
            'id': 6,
            'name': 'Sword II',
            'type': 'weapon',
            'damage': [50, 68],
            'epCost': 5,
            'critChance': 0.13,
            'value': 450,
            'stackable': False,
            'tier': 2,
            'quantity': 0,
            'index': 0,
        },

        {
            'id': 7,
            'name': 'Sword III',
            'type': 'weapon',
            'damage': [70, 88],
            'epCost': 10,
            'critChance': 0.11,
            'value': 650,
            'stackable': False,
            'tier': 3,
            'quantity': 0,
            'index': 0,
        },

        {
            'id': 8,
            'name': 'Sword IV',
            'type': 'weapon',
            'damage': [90, 108],
            'epCost': 20,
            'critChance': 0.09,
            'value': 1200,
            'stackable': False,
            'tier': 4,
            'quantity': 0,
            'index': 0,
        },

        {
            'id': 9,
            'name': 'Sword V',
            'type': 'weapon',
            'damage': [110, 130],
            'epCost': 40,
            'critChance': 0.07,
            'value': 1700,
            'stackable': False,
            'tier': 5,
            'quantity': 0,
            'index': 0,
        },

        {
            'id': 10,
            'name': 'Small Ork Sword',
            'type': 'weapon',
            'damage': [10, 24],
            'epCost': 2,
            'critChance': 0.10,
            'value': 100,
            'stackable': False,
            'tier': 1,
            'quantity': 0,
            'index': 0,
        },

        {
            'id': 11,
            'name': 'Medium Ork Sword',
            'type': 'weapon',
            'damage': [24, 50],
            'epCost': 3,
            'critChance': 0.10,
            'value': 100,
            'stackable': False,
            'tier': 2,
            'quantity': 0,
            'index': 0,
        },

        {
            'id': 12,
            'name': 'Broken Sword',
            'type': 'weapon',
            'damage': [6, 10],
            'epCost': 1,
            'critChance': 0.00,
            'value': 10,
            'stackable': False,
            'tier': 1,
            'quantity': 0,
            'index': 0,
        },
        
        {
            'id': 13,
            'name': 'Large Ork Sword',
            'type': 'weapon',
            'damage': [52, 70],
            'epCost': 5,
            'critChance': 0.09,
            'value': 300,
            'stackable': False,
            'tier': 3,
            'quantity': 0,
            'index': 0,
        },

        {
            'id': 69,
            'name': 'EGG',
            'type': 'weapon',
            'damage': [100, 120],
            'epCost': 75,
            'critChance': 0.25,
            'value': 1,
            'stackable': False,
            'tier': 5,
            'quantity': 0, 
            'index': 0,
        },
    ],

    'armor': [
        {
            'id': 12,
            'name': 'Armor I',
            'type': 'armor',
            'hp': 200,
            'hpMax': 200,
            'disperse': 0.50,
            'value': 200,
            'stackable': False,
            'isBroken': False,
            'tier': 1,
            'quantity': 0,
            'index': 0,
        },

        {
            'id': 13,
            'name': 'Armor II',
            'type': 'armor',
            'hp': 300,
            'hpMax': 300,
            'disperse': 0.54,
            'value': 400,
            'stackable': False,
            'isBroken': False,
            'tier': 2,
            'quantity': 0,
            'index': 0,
        },

        {
            'id': 14,
            'name': 'Armor III',
            'type': 'armor',
            'hp': 400,
            'hpMax': 400,
            'disperse': 0.58,
            'value': 600,
            'stackable': False,
            'isBroken': False,
            'tier': 3,
            'quantity': 0,
            'index': 0,
        },

        {
            'id': 15,
            'name': 'Armor IV',
            'type': 'armor',
            'hp': 500,
            'hpMax': 500,
            'disperse': 0.62,
            'value': 800,
            'stackable': False,
            'isBroken': False,
            'tier': 4,
            'quantity': 0,
            'index': 0,
        },

        {
            'id': 16,
            'name': 'Armor V',
            'type': 'armor',
            'hp': 600,
            'hpMax': 600,
            'disperse': 0.66,
            'value': 1000,
            'stackable': False,
            'isBroken': False,
            'tier': 5,
            'quantity': 0,
            'index': 0,
        },
    ],

    'shields': [
        {
            'id': 17,
            'name': 'Shield I',
            'type': 'shield',
            'hp': 50,
            'hpMax': 50,
            'epCost': 4,
            'disperse': 0.70,
            'value': 100,
            'stackable': False,
            'isBroken': False,
            'tier': 1,
            'quantity': 0,
            'index': 0,
        },

        {
            'id': 18,
            'name': 'Shield II',
            'type': 'shield',
            'hp': 100,
            'hpMax': 100,
            'epCost': 8,
            'disperse': 0.77,
            'value': 200,
            'stackable': False,
            'isBroken': False,
            'tier': 2,
            'quantity': 0,
            'index': 0,
        },

        {
            'id': 19,
            'name': 'Shield III',
            'type': 'shield',
            'hp': 200,
            'hpMax': 200,
            'epCost': 16,
            'disperse': 0.84,
            'value': 300,
            'stackable': False,
            'isBroken': False,
            'tier': 3,
            'quantity': 0,
            'index': 0,
        },

        {
            'id': 20,
            'name': 'Shield IV',
            'type': 'shield',
            'hp': 300,
            'hpMax': 300,
            'epCost': 32,
            'disperse': 0.91,
            'value': 400,
            'stackable': False,
            'isBroken': False,
            'tier': 4,
            'quantity': 0,
            'index': 0,
        },

        {
            'id': 21,
            'name': 'Shield V',
            'type': 'shield',
            'hp': 400,
            'hpMax': 400,
            'epCost': 64,
            'disperse': 0.98,
            'value': 500,
            'stackable': False,
            'isBroken': False,
            'tier': 5,
            'quantity': 0,
            'index': 0,
        },
    ],

    'spells': [
        {
            'id': 22,
            'name': 'Fireball spell I',
            'type': 'spell',
            'spellType': 'damage',
            'duration': 1,
            'damage': [12, 14],
            'critChance': 0.13,
            'stackable': False,
            'mpCost': 4,
            'tier': 1,
            'index': 0,
        },

        {
            'id': 23,
            'name': 'Fireball spell II',
            'type': 'spell',
            'spellType': 'damage',
            'duration': 1,
            'damage': [21, 25],
            'critChance': 0.11,
            'stackable': False,
            'mpCost': 10,
            'tier': 2,
            'index': 0,
        },

        {
            'id': 24,
            'name': 'Fireball spell III',
            'type': 'spell',
            'spellType': 'damage',
            'duration': 1,
            'damage': [30, 36],
            'critChance': 0.09,
            'stackable': False,
            'mpCost': 16,
            'tier': 3,
            'index': 0,
        },

        {
            'id': 25,
            'name': 'Spell of Healing I',
            'type': 'spell',
            'spellType': 'healing',
            'duration': 1,
            'healing': 200,
            'critChance': 0.00,
            'stackable': False,
            'mpCost': 15,
            'tier': 2,
            'index': 0,
        },

        {
            'id': 26,
            'name': 'Spell of Healing II',
            'type': 'spell',
            'spellType': 'healing',
            'duration': 1,
            'healing': 400,
            'critChance': 0.00,
            'stackable': False,
            'mpCost': 35,
            'tier': 3,
            'index': 0,
        },

        # {
        #     'id': 27,
        #     'name': 'Healing field spell',
        #     'type': 'spell',
        #     'spellType': 'healing',
        #     'duration': 3,
        #     'healing': 75,
        #     'critChance': 0.00,
        #     'stackable': False,
        #     'mpCost': 45,
        #     'tier': 4,
        #     'index': 0,
        # },

        {
            'id': 28,
            'name': 'Defence spell I',
            'type': 'spell',
            'spellType': 'block',
            'duration': 1,
            'block': 50,
            'disperse': 1.00,
            'critChance': 0.00,
            'stackable': False,
            'mpCost': 35,
            'tier': 2,
            'index': 0,
        },

        {
            'id': 29,
            'name': 'Defence spell II',
            'type': 'spell',
            'spellType': 'block',
            'duration': 1,
            'block': 100,
            'disperse': 1.00,
            'critChance': 0.00,
            'stackable': False,
            'mpCost': 55,
            'tier': 3,
            'index': 0,
        },

        # {
        #     'id': 30,
        #     'name': 'Defence field spell',
        #     'type': 'spell',
        #     'spellType': 'block',
        #     'duration': 3,
        #     'block': 100,
        #     'disperse': 0.80,
        #     'critChance': 0.00,
        #     'stackable': False,
        #     'mpCost': 70,
        #     'tier': 4,
        #     'index': 0,
        # },
    ],
}
